#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Principal.Resource", IsApplication=true)]

namespace Principal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calculator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int contactos = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int conversormon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int conversorr = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int paint = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int traductor = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int btnBorrar = 2131034130;
			
			// aapt resource value: 0x7f050034
			public const int btnBuscar = 2131034164;
			
			// aapt resource value: 0x7f050048
			public const int btnCalculadora = 2131034184;
			
			// aapt resource value: 0x7f050044
			public const int btnCalendario = 2131034180;
			
			// aapt resource value: 0x7f05000d
			public const int btnCero = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int btnCinco = 2131034118;
			
			// aapt resource value: 0x7f050043
			public const int btnContactos = 2131034179;
			
			// aapt resource value: 0x7f050045
			public const int btnConversorMoneda = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int btnConversorUnidades = 2131034182;
			
			// aapt resource value: 0x7f05002c
			public const int btnConvertir = 2131034156;
			
			// aapt resource value: 0x7f05000f
			public const int btnCos = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int btnCuatro = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int btnDiferencia = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int btnDivision = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int btnDos = 2131034114;
			
			// aapt resource value: 0x7f050025
			public const int btnGestion = 2131034149;
			
			// aapt resource value: 0x7f050015
			public const int btnGraficar = 2131034133;
			
			// aapt resource value: 0x7f05003b
			public const int btnGraficarParametro = 2131034171;
			
			// aapt resource value: 0x7f050024
			public const int btnGuardar = 2131034148;
			
			// aapt resource value: 0x7f050014
			public const int btnIgual = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int btnNueve = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int btnOcho = 2131034122;
			
			// aapt resource value: 0x7f050047
			public const int btnPaint = 2131034183;
			
			// aapt resource value: 0x7f05000c
			public const int btnProducto = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int btnReiniciar = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int btnSeis = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int btnSen = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int btnSiete = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int btnSuma = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int btnTan = 2131034128;
			
			// aapt resource value: 0x7f05003f
			public const int btnTraducir = 2131034175;
			
			// aapt resource value: 0x7f050049
			public const int btnTraductor = 2131034185;
			
			// aapt resource value: 0x7f050003
			public const int btnTres = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int btnUno = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int etApellidos = 2131034139;
			
			// aapt resource value: 0x7f050033
			public const int etBuscar = 2131034163;
			
			// aapt resource value: 0x7f050023
			public const int etCorreo = 2131034147;
			
			// aapt resource value: 0x7f050019
			public const int etNombres = 2131034137;
			
			// aapt resource value: 0x7f05003e
			public const int etPalabra = 2131034174;
			
			// aapt resource value: 0x7f05001d
			public const int etTelefono = 2131034141;
			
			// aapt resource value: 0x7f050027
			public const int etValor = 2131034151;
			
			// aapt resource value: 0x7f050017
			public const int etcedula = 2131034135;
			
			// aapt resource value: 0x7f050038
			public const int parA = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int parB = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int parC = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int plot_view = 2131034172;
			
			// aapt resource value: 0x7f050028
			public const int radioGroup1 = 2131034152;
			
			// aapt resource value: 0x7f05002b
			public const int rbDolares = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int rbEuros = 2131034154;
			
			// aapt resource value: 0x7f050030
			public const int rbGalones = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int rbLitros = 2131034161;
			
			// aapt resource value: 0x7f05002e
			public const int rbMillas = 2131034158;
			
			// aapt resource value: 0x7f050029
			public const int rbPesos = 2131034153;
			
			// aapt resource value: 0x7f05002f
			public const int rbkilometros = 2131034159;
			
			// aapt resource value: 0x7f05001f
			public const int rgFijo = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int rgMovil = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int rgMovill = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int rgTrabajo = 2131034144;
			
			// aapt resource value: 0x7f050026
			public const int textView1 = 2131034150;
			
			// aapt resource value: 0x7f05001c
			public const int textView2 = 2131034140;
			
			// aapt resource value: 0x7f050022
			public const int textView5 = 2131034146;
			
			// aapt resource value: 0x7f05003d
			public const int txtAbaratar = 2131034173;
			
			// aapt resource value: 0x7f05001a
			public const int txtApellidos = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int txtCedula = 2131034134;
			
			// aapt resource value: 0x7f050037
			public const int txtCorreo = 2131034167;
			
			// aapt resource value: 0x7f05002d
			public const int txtInfo = 2131034157;
			
			// aapt resource value: 0x7f050018
			public const int txtNombres = 2131034136;
			
			// aapt resource value: 0x7f050041
			public const int txtPalabras = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int txtPalabrasIngles = 2131034178;
			
			// aapt resource value: 0x7f050000
			public const int txtResul = 2131034112;
			
			// aapt resource value: 0x7f050032
			public const int txtResultado = 2131034162;
			
			// aapt resource value: 0x7f050035
			public const int txtTelefono = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int txtTipo = 2131034166;
			
			// aapt resource value: 0x7f050040
			public const int txtTraduccion = 2131034176;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layoutCalculadora = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layoutContactos = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layoutConversorMoneda = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layoutConversorUnidad = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layoutGestionContactos = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layoutGrafica = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int layoutTraductor = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
